/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlchxd;

/**
 *
 * @author Admin
 */
public class FrmRegister extends javax.swing.JPanel {

    /**
     * Creates new form FrmSignUp
     */
    public FrmRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel_DangNhap = new javax.swing.JPanel();
        Username_Field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Password_Field = new javax.swing.JPasswordField();
        Label_DangNhap = new java.awt.Label();
        Label_MatKhau = new java.awt.Label();
        Label_TaiKhoan = new java.awt.Label();
        SignUp_btn = new javax.swing.JButton();
        CheckBox_ShowPass = new javax.swing.JCheckBox();
        Password_Field1 = new javax.swing.JPasswordField();
        Label_MatKhau1 = new java.awt.Label();
        Panel_Logo = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Label_Logo = new java.awt.Label();
        Label_Slogan = new java.awt.Label();

        Panel_DangNhap.setBackground(new java.awt.Color(255, 255, 255));
        Panel_DangNhap.setPreferredSize(new java.awt.Dimension(500, 500));

        Username_Field.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Username_Field.setForeground(new java.awt.Color(0, 102, 51));
        Username_Field.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 51, 51)));
        Username_Field.setPreferredSize(new java.awt.Dimension(80, 30));
        Username_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_FieldActionPerformed(evt);
            }
        });

        Password_Field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Password_Field.setForeground(new java.awt.Color(0, 102, 51));
        Password_Field.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 102, 102)));
        Password_Field.setPreferredSize(new java.awt.Dimension(100, 30));
        Password_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_FieldActionPerformed(evt);
            }
        });

        Label_DangNhap.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Label_DangNhap.setForeground(new java.awt.Color(0, 102, 102));
        Label_DangNhap.setText("ĐĂNG KÝ");

        Label_MatKhau.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Label_MatKhau.setText("Nhập mật khẩu");

        Label_TaiKhoan.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Label_TaiKhoan.setText("Tài khoản");

        SignUp_btn.setBackground(new java.awt.Color(0, 149, 118));
        SignUp_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignUp_btn.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_btn.setText("ĐĂNG KÝ");
        SignUp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_btnActionPerformed(evt);
            }
        });

        CheckBox_ShowPass.setText("Hiển thị mật khẩu");
        CheckBox_ShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_ShowPassActionPerformed(evt);
            }
        });

        Password_Field1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Password_Field1.setForeground(new java.awt.Color(0, 102, 51));
        Password_Field1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 102, 102)));
        Password_Field1.setPreferredSize(new java.awt.Dimension(100, 30));
        Password_Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_Field1ActionPerformed(evt);
            }
        });

        Label_MatKhau1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Label_MatKhau1.setText("Nhập lại mật khẩu");

        javax.swing.GroupLayout Panel_DangNhapLayout = new javax.swing.GroupLayout(Panel_DangNhap);
        Panel_DangNhap.setLayout(Panel_DangNhapLayout);
        Panel_DangNhapLayout.setHorizontalGroup(
            Panel_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DangNhapLayout.createSequentialGroup()
                .addGroup(Panel_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_DangNhapLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(Label_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_DangNhapLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(Panel_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_DangNhapLayout.createSequentialGroup()
                                .addGroup(Panel_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Panel_DangNhapLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Label_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Password_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Panel_DangNhapLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Label_MatKhau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Password_Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DangNhapLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Panel_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DangNhapLayout.createSequentialGroup()
                        .addComponent(CheckBox_ShowPass)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DangNhapLayout.createSequentialGroup()
                        .addComponent(Label_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DangNhapLayout.createSequentialGroup()
                        .addComponent(SignUp_btn)
                        .addGap(187, 187, 187))))
        );
        Panel_DangNhapLayout.setVerticalGroup(
            Panel_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DangNhapLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Label_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Label_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Panel_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_DangNhapLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(Panel_DangNhapLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Label_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Label_MatKhau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Password_Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckBox_ShowPass)
                .addGap(24, 24, 24)
                .addComponent(SignUp_btn)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        Panel_Logo.setBackground(new java.awt.Color(0, 102, 102));
        Panel_Logo.setPreferredSize(new java.awt.Dimension(500, 500));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logo3.png"))); // NOI18N

        Label_Logo.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        Label_Logo.setForeground(new java.awt.Color(255, 255, 255));
        Label_Logo.setText("HUY NAM");

        Label_Slogan.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        Label_Slogan.setForeground(new java.awt.Color(255, 255, 255));
        Label_Slogan.setText("THƯƠNG HIỆU UY TÍN HÀNG ĐẦU VIỆT NAM");

        javax.swing.GroupLayout Panel_LogoLayout = new javax.swing.GroupLayout(Panel_Logo);
        Panel_Logo.setLayout(Panel_LogoLayout);
        Panel_LogoLayout.setHorizontalGroup(
            Panel_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LogoLayout.createSequentialGroup()
                .addGroup(Panel_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_LogoLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(Logo))
                    .addGroup(Panel_LogoLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(Label_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_LogoLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(Label_Slogan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        Panel_LogoLayout.setVerticalGroup(
            Panel_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Slogan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Panel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panel_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_DangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Username_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_FieldActionPerformed

    }//GEN-LAST:event_Username_FieldActionPerformed

    private void Password_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_FieldActionPerformed

    private void SignUp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_btnActionPerformed

    private void CheckBox_ShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_ShowPassActionPerformed
        if (CheckBox_ShowPass.isSelected()) {
            // Nếu checkbox được chọn, hiển thị mật khẩu
            Password_Field.setEchoChar((char) 0); // Hiển thị mật khẩu
            Password_Field1.setEchoChar((char) 0);
        } else {
            // Nếu checkbox không được chọn, ẩn mật khẩu
            Password_Field.setEchoChar('●'); // Đặt lại ký tự ẩn
            Password_Field1.setEchoChar('●');
        }
    }//GEN-LAST:event_CheckBox_ShowPassActionPerformed

    private void Password_Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_Field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_Field1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox_ShowPass;
    private java.awt.Label Label_DangNhap;
    private java.awt.Label Label_Logo;
    private java.awt.Label Label_MatKhau;
    private java.awt.Label Label_MatKhau1;
    private java.awt.Label Label_Slogan;
    private java.awt.Label Label_TaiKhoan;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Panel_DangNhap;
    private javax.swing.JPanel Panel_Logo;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JPasswordField Password_Field1;
    private javax.swing.JButton SignUp_btn;
    private javax.swing.JTextField Username_Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
