/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package baitap1;

import javax.swing.*;
import java.awt.Graphics;
import java.awt.Graphics2D;
/**
 *
 * @author doanhuy
 */
public class imgPanel extends javax.swing.JPanel {

    /**
     * Creates new form imgPanel
     */
    public imgPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        // Vẽ hình ảnh làm nền cho JPanel
        if (backgroundImage != null) {
            g.drawImage(((ImageIcon) backgroundImage).getImage(), 0, 0, getWidth(), getHeight(), this);
        }

    }
    
    public void setBackgroundImage(Icon img)   {
        this.backgroundImage = img;
        revalidate();
        repaint();
    }
    public Icon getBackgroundImage() {
        return backgroundImage;
    }
    
    private Icon backgroundImage;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
