/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

//Cong viec chua xong:
// Chua co tim kiem


package qlchxd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;

import java.text.SimpleDateFormat;
import java.text.ParseException;

/**
 *
 * @author Admin
 */
public class Payments extends javax.swing.JInternalFrame {

    /**
     * Creates new form Payments
     */
    public Payments() {
        initComponents();
        fetchData();
        
        Panel_ThongTin.setVisible(false);
        Panel_ChucNang.setVisible(false);
        Panel_DuLieu.setPreferredSize(new java.awt.Dimension(1000, 600));
    }

    private void fetchData() {
        String connectionUrl = "jdbc:sqlserver://HOMHINHHA\\SQLEXPRESS:1433;databaseName=QLCHXEDAP;trustServerCertificate=true";
        String user = "sa"; // Thay bằng username của bạn
        String password = "123456789"; // Thay bằng password của bạn

        try (Connection conn = DriverManager.getConnection(connectionUrl, user, password)) {
            String sql = "SELECT MaThanhToan, MaXe, MaKH, NgayThanhToan, PhuongThucThanhToan, SoLuongXeMua, ThanhTien FROM ThanhToan";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            // Tạo mô hình cho JTable
            DefaultTableModel model = (DefaultTableModel) Data_Payment.getModel();
            model.setRowCount(0); // Xóa hết dữ liệu cũ

            // Thêm dữ liệu vào JTable
            while (rs.next()) {
                Object[] row = {
                    rs.getString("MaThanhToan"),
                    rs.getString("MaXe"),
                    rs.getString("MaKH"),
                    rs.getDate("NgayThanhToan"),
                    rs.getString("PhuongThucThanhToan"),
                    rs.getInt("SoLuongXeMua"),
                    rs.getFloat("ThanhTien")
                };
                model.addRow(row);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    } 
    
    private void SearchData() {
        String connectionUrl = "jdbc:sqlserver://HOMHINHHA\\SQLEXPRESS:1433;databaseName=QLCHXEDAP;trustServerCertificate=true";
        String user = "sa"; // Thay bằng username của bạn
        String password = "123456789"; // Thay bằng password của bạn

        try (Connection conn = DriverManager.getConnection(connectionUrl, user, password)) {
            String sql = "SELECT MaThanhToan, MaXe, MaKH, NgayThanhToan, PhuongThucThanhToan, SoLuongXeMua, ThanhTien FROM ThanhToan WHERE MaThanhToan LIKE N'%"+Search_field.getText()+"%' or MaXe LIKE N'%"+Search_field.getText()+"%' or MaKH LIKE N'%"+Search_field.getText()+"%' or NgayThanhToan LIKE N'%"+Search_field.getText()+"%' or PhuongThucThanhToan LIKE N'%"+Search_field.getText()+"%' ";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            // Tạo mô hình cho JTable
            DefaultTableModel model = (DefaultTableModel) Data_Payment.getModel();
            model.setRowCount(0); // Xóa hết dữ liệu cũ

            // Thêm dữ liệu vào JTable
            while (rs.next()) {
                Object[] row = {
                    rs.getString("MaThanhToan"),
                    rs.getString("MaXe"),
                    rs.getString("MaKH"),
                    rs.getDate("NgayThanhToan"),
                    rs.getString("PhuongThucThanhToan"),
                    rs.getInt("SoLuongXeMua"),
                    rs.getFloat("ThanhTien")
                };
                model.addRow(row);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_ChucNang = new javax.swing.JPanel();
        Add_btn = new javax.swing.JButton();
        Delete_btn = new javax.swing.JButton();
        Update_btn = new javax.swing.JButton();
        ChucNang = new javax.swing.JLabel();
        Panel_ThongTin = new javax.swing.JPanel();
        DatePay_Label = new javax.swing.JLabel();
        IDPay_Field = new javax.swing.JTextField();
        IDCus_Label = new javax.swing.JLabel();
        IDCus_Field = new javax.swing.JTextField();
        IDTrans_Field = new javax.swing.JTextField();
        MethodPay_Label = new javax.swing.JLabel();
        IDTrans_Label = new javax.swing.JLabel();
        Pay_Label = new javax.swing.JLabel();
        ThongTin = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        PayPrice_Label = new javax.swing.JLabel();
        Price_Field = new javax.swing.JTextField();
        Quantity_Label = new javax.swing.JLabel();
        QuantityTrans_Field = new javax.swing.JTextField();
        Panel_DuLieu = new javax.swing.JPanel();
        Search_Label = new javax.swing.JLabel();
        Search_field = new javax.swing.JTextField();
        Search_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Data_Payment = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("QUẢN LÝ BÁN HÀNG");
        setPreferredSize(new java.awt.Dimension(1000, 600));

        Panel_ChucNang.setBackground(new java.awt.Color(0, 102, 102));
        Panel_ChucNang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Panel_ChucNang.setForeground(new java.awt.Color(255, 255, 255));

        Add_btn.setText("Thêm ");
        Add_btn.setPreferredSize(new java.awt.Dimension(80, 25));
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });

        Delete_btn.setText("Xóa");
        Delete_btn.setPreferredSize(new java.awt.Dimension(80, 25));
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });

        Update_btn.setText("Cập nhật");
        Update_btn.setPreferredSize(new java.awt.Dimension(80, 25));
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        ChucNang.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ChucNang.setForeground(new java.awt.Color(255, 255, 255));
        ChucNang.setText("Chức năng");

        javax.swing.GroupLayout Panel_ChucNangLayout = new javax.swing.GroupLayout(Panel_ChucNang);
        Panel_ChucNang.setLayout(Panel_ChucNangLayout);
        Panel_ChucNangLayout.setHorizontalGroup(
            Panel_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ChucNangLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        Panel_ChucNangLayout.setVerticalGroup(
            Panel_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ChucNangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        Panel_ThongTin.setBackground(new java.awt.Color(0, 102, 102));
        Panel_ThongTin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Panel_ThongTin.setForeground(new java.awt.Color(255, 255, 255));
        Panel_ThongTin.setPreferredSize(new java.awt.Dimension(500, 600));

        DatePay_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DatePay_Label.setForeground(new java.awt.Color(255, 255, 255));
        DatePay_Label.setText("Nhập ngày TT");

        IDPay_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDPay_FieldActionPerformed(evt);
            }
        });

        IDCus_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IDCus_Label.setForeground(new java.awt.Color(255, 255, 255));
        IDCus_Label.setText("Nhập mã KH");

        IDCus_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDCus_FieldActionPerformed(evt);
            }
        });

        IDTrans_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTrans_FieldActionPerformed(evt);
            }
        });

        MethodPay_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MethodPay_Label.setForeground(new java.awt.Color(255, 255, 255));
        MethodPay_Label.setText("Phương thức TT");

        IDTrans_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IDTrans_Label.setForeground(new java.awt.Color(255, 255, 255));
        IDTrans_Label.setText("Nhập mã xe");

        Pay_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Pay_Label.setForeground(new java.awt.Color(255, 255, 255));
        Pay_Label.setText("Nhập mã TT");

        ThongTin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ThongTin.setForeground(new java.awt.Color(255, 255, 255));
        ThongTin.setText("Thông tin");

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chuyển khoản", "Tiền mặt" }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });

        PayPrice_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PayPrice_Label.setForeground(new java.awt.Color(255, 255, 255));
        PayPrice_Label.setText("Tiền thanh toán");

        Price_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price_FieldActionPerformed(evt);
            }
        });

        Quantity_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Quantity_Label.setForeground(new java.awt.Color(255, 255, 255));
        Quantity_Label.setText("Số lượng xe");

        QuantityTrans_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTrans_FieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_ThongTinLayout = new javax.swing.GroupLayout(Panel_ThongTin);
        Panel_ThongTin.setLayout(Panel_ThongTinLayout);
        Panel_ThongTinLayout.setHorizontalGroup(
            Panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ThongTinLayout.createSequentialGroup()
                .addGroup(Panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ThongTinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_ThongTinLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(Panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pay_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDTrans_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MethodPay_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(IDCus_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DatePay_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PayPrice_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Quantity_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDCus_Field)
                            .addComponent(IDTrans_Field)
                            .addComponent(IDPay_Field)
                            .addComponent(QuantityTrans_Field)
                            .addComponent(Price_Field)
                            .addComponent(ComboBox, 0, 163, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        Panel_ThongTinLayout.setVerticalGroup(
            Panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pay_Label)
                    .addComponent(IDPay_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDTrans_Label)
                    .addComponent(IDTrans_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDCus_Label)
                    .addComponent(IDCus_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(DatePay_Label)
                .addGap(18, 18, 18)
                .addGroup(Panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MethodPay_Label)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantity_Label)
                    .addComponent(QuantityTrans_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PayPrice_Label)
                    .addComponent(Price_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        Panel_DuLieu.setBackground(new java.awt.Color(0, 102, 102));
        Panel_DuLieu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Panel_DuLieu.setForeground(new java.awt.Color(255, 255, 255));
        Panel_DuLieu.setPreferredSize(new java.awt.Dimension(500, 600));
        Panel_DuLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_DuLieuMouseClicked(evt);
            }
        });

        Search_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Search_Label.setForeground(new java.awt.Color(255, 255, 255));
        Search_Label.setText("Tìm kiếm");

        Search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_fieldActionPerformed(evt);
            }
        });

        Search_btn.setText("Tìm kiếm");
        Search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btnActionPerformed(evt);
            }
        });

        Data_Payment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã thanh toán", "Mã xe", "Mã khách hàng", "Ngày thanh toán", "Phương thức thann toán", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Data_Payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Data_PaymentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Data_Payment);

        javax.swing.GroupLayout Panel_DuLieuLayout = new javax.swing.GroupLayout(Panel_DuLieu);
        Panel_DuLieu.setLayout(Panel_DuLieuLayout);
        Panel_DuLieuLayout.setHorizontalGroup(
            Panel_DuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DuLieuLayout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addComponent(Search_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Search_btn)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DuLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        Panel_DuLieuLayout.setVerticalGroup(
            Panel_DuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DuLieuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Panel_DuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_Label)
                    .addComponent(Search_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_ChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_DuLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_DuLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel_ThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel_ChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
        String connectionUrl = "jdbc:sqlserver://HOMHINHHA\\SQLEXPRESS:1433;databaseName=QLCHXEDAP;trustServerCertificate=true";
        String user = "sa"; 
        String password = "123456789"; 

        try (Connection conn = DriverManager.getConnection(connectionUrl, user, password)) {
            String sql = "INSERT INTO ThanhToan (MaThanhToan, MaXe, MaKH, NgayThanhToan, PhuongThucThanhToan, SoLuongXeMua, ThanhTien) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            pstmt.setString(1,IDPay_Field.getText()); 
            pstmt.setString(2, IDTrans_Field.getText());
            pstmt.setString(3, IDCus_Field.getText());

            // Chuyển đổi java.util.Date sang java.sql.Date
            pstmt.setDate(4, new java.sql.Date(DateChooser.getDate().getTime()));

            // Sử dụng getSelectedItem().toString() cho JComboBox
            pstmt.setString(5, ComboBox.getSelectedItem().toString()); 
            pstmt.setInt(6, Integer.parseInt(QuantityTrans_Field.getText())); 
            pstmt.setFloat(7, Float.parseFloat(Price_Field.getText())); 

            pstmt.executeUpdate(); 
            fetchData(); 

            ClearText();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Add_btnActionPerformed

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
       
        String maTT = IDPay_Field.getText();

        String connectionUrl = "jdbc:sqlserver://HOMHINHHA\\SQLEXPRESS:1433;databaseName=QLCHXEDAP;trustServerCertificate=true";
        String user = "sa";
        String password = "123456789";

        try (Connection conn = DriverManager.getConnection(connectionUrl, user, password)) {
            String sql = "DELETE FROM ThanhToan WHERE MaKH = ?";
            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                pstmt.setString(1, maTT);
                pstmt.executeUpdate();
                fetchData();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Delete_btnActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
        String connectionUrl = "jdbc:sqlserver://HOMHINHHA\\SQLEXPRESS:1433;databaseName=QLCHXEDAP;trustServerCertificate=true";
        String user = "sa"; 
        String password = "123456789"; 

        try (Connection conn = DriverManager.getConnection(connectionUrl, user, password)) {
            String sql = "UPDATE ThanhToan SET MaXe = ?, MaKH = ?, NgayThanhToan = ?, PhuongThucThanhToan = ?, SoLuongXeMua = ?, ThanhTien = ? WHERE MaThanhToan = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            pstmt.setString(1,IDTrans_Field.getText()); // Thay đổi ID xe
            pstmt.setString(2,IDCus_Field.getText()); // ID khách hàng
            pstmt.setDate(3, new java.sql.Date(DateChooser.getDate().getTime())); // Ngày thanh toán
            pstmt.setString(4, ComboBox.getSelectedItem().toString()); // Phương thức thanh toán
            pstmt.setInt(5, Integer.parseInt(QuantityTrans_Field.getText())); // Số lượng xe mua
            pstmt.setFloat(6, Float.parseFloat(Price_Field.getText())); // Thành tiền
            pstmt.setString(7,IDPay_Field.getText()); // MaThanhToan

            pstmt.executeUpdate(); // Thực thi truy vấn
            fetchData(); // Cập nhật lại dữ liệu hiển thị
            ClearText(); 
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Update_btnActionPerformed

    private void IDPay_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDPay_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDPay_FieldActionPerformed

    private void IDCus_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDCus_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDCus_FieldActionPerformed

    private void IDTrans_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTrans_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTrans_FieldActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void Price_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Price_FieldActionPerformed

    private void QuantityTrans_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityTrans_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityTrans_FieldActionPerformed

    private void Search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_fieldActionPerformed

    private void Search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_btnActionPerformed
        SearchData();
    }//GEN-LAST:event_Search_btnActionPerformed

    private void Data_PaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Data_PaymentMouseClicked
        int i = Data_Payment.getSelectedRow();
        IDPay_Field.setText(Data_Payment.getValueAt(i, 0).toString());
        IDTrans_Field.setText(Data_Payment.getValueAt(i, 1).toString());
        IDCus_Field.setText(Data_Payment.getValueAt(i, 2).toString());
        QuantityTrans_Field.setText(Data_Payment.getValueAt(i, 5).toString());
        Price_Field.setText(Data_Payment.getValueAt(i, 6).toString());
        String dateStr = Data_Payment.getValueAt(i, 3).toString();
        try {
            // Định dạng ngày tháng (định dạng này có thể thay đổi theo định dạng của dữ liệu)
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date date = dateFormat.parse(dateStr);
            DateChooser.setDate(date); // Đặt giá trị cho DateChooser
        } catch (ParseException e) {
            e.printStackTrace();
        }

        ComboBox.setSelectedItem(Data_Payment.getValueAt(i, 4).toString());
    }//GEN-LAST:event_Data_PaymentMouseClicked

    private void Panel_DuLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_DuLieuMouseClicked
        boolean isVisible = Panel_ThongTin.isVisible() && Panel_ChucNang.isVisible();

        // Đổi trạng thái hiển thị của các panel
        Panel_ThongTin.setVisible(!isVisible);
        Panel_ChucNang.setVisible(!isVisible);

        // Điều chỉnh kích thước của Panel_DuLieu dựa trên trạng thái hiển thị
        if (isVisible) {
            Panel_DuLieu.setPreferredSize(new java.awt.Dimension(1000, 600)); // Phóng to 
        } else {
            Panel_DuLieu.setPreferredSize(new java.awt.Dimension(500, 600));  // Trả về 
        }

        // Làm mới lại layout
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_Panel_DuLieuMouseClicked

    public void ClearText() {
        IDPay_Field.setText("");
        IDTrans_Field.setText("");
        IDCus_Field.setText("");
        DateChooser.setDate(null);

        QuantityTrans_Field.setText("");
        Price_Field.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn;
    private javax.swing.JLabel ChucNang;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JTable Data_Payment;
    private javax.swing.JLabel DatePay_Label;
    private javax.swing.JButton Delete_btn;
    private javax.swing.JTextField IDCus_Field;
    private javax.swing.JLabel IDCus_Label;
    private javax.swing.JTextField IDPay_Field;
    private javax.swing.JTextField IDTrans_Field;
    private javax.swing.JLabel IDTrans_Label;
    private javax.swing.JLabel MethodPay_Label;
    private javax.swing.JPanel Panel_ChucNang;
    private javax.swing.JPanel Panel_DuLieu;
    private javax.swing.JPanel Panel_ThongTin;
    private javax.swing.JLabel PayPrice_Label;
    private javax.swing.JLabel Pay_Label;
    private javax.swing.JTextField Price_Field;
    private javax.swing.JTextField QuantityTrans_Field;
    private javax.swing.JLabel Quantity_Label;
    private javax.swing.JLabel Search_Label;
    private javax.swing.JButton Search_btn;
    private javax.swing.JTextField Search_field;
    private javax.swing.JLabel ThongTin;
    private javax.swing.JButton Update_btn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
